version: "3.9"
services: 
    mongodb:
        image: "mongo"
        #entrypoint: "for i in /app/data/csv/*.csv; do mongoimport --db Binance --type --headerline --ignoreBlanks --file $i; done"
    
    cryptoapi:
        build: .
        depends_on: 
            - mongodb
        ports:
            - "5001:5001"